version: "3.1"
services:
  checkmk:
    container_name: monitoring
    image: checkmk/check-mk-raw:latest
    # restart: always
    environment: []
      # - MAIL_RELAY_HOST="" 
      # - CMK_LIVESTATUS_TCP=on
    ports:
      - 127.0.0.1:8080:5000
      # - 127.0.0.1:162:162/udp
      # - 127.0.0.1:514:514/udp
      # - 127.0.0.1:514:514/tcp
    volumes:
      - ./.data/monitoring/omd/sites:/omd/sites
      - /etc/localtime:/etc/localtime:ro
